// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class mig_addimage_file : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_addimage_file));
        
        string IMigrationMetadata.Id
        {
            get { return "202205030954546_mig_addimage_file"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
